# Generated by Django 4.0.3 on 2022-03-18 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='"users"',
        ),
    ]
