# Generated by Django 4.0.3 on 2022-03-18 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bodyparts',
            table='"body_parts"',
        ),
        migrations.AlterModelTable(
            name='exercisebodyparts',
            table='"exercise_body_parts"',
        ),
        migrations.AlterModelTable(
            name='exercises',
            table='"exercises"',
        ),
    ]
