# Generated by Django 4.0.3 on 2022-03-18 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_alter_bodyparts_table_alter_exercisebodyparts_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bodyparts',
            table='body_parts',
        ),
        migrations.AlterModelTable(
            name='exercisebodyparts',
            table='exercise_body_parts',
        ),
        migrations.AlterModelTable(
            name='exercises',
            table='exercises',
        ),
    ]
